export const STATE_LABELS: Record<string, string> = {
  consented: "Consented",
  context: "Context",
  discovery: "Discovery",
  confirmation: "Confirmation",
  eligibility_check: "Eligibility check",
  parked: "Parked",
  baseline_frozen: "Baseline frozen",
  crux: "Crux",
  pre_evidence_recorded: "Pre-evidence recorded",
  assigned: "Assigned",
  pending_review: "Pending review",
  refused: "Refused",
  approved: "Approved",
  delivered: "Delivered",
  ack_recorded: "Ack recorded",
  measured: "Measured",
  followup_due: "Follow-up due",
  complete: "Complete",
  withdrawn: "Withdrawn",
};
